### ISSUE TITLE
Error at configure step in CMake

### ISSUE THREAD

**Issue by arrufat** [gammasoft71/Examples_Gtkmm#1]
First of all, thank you for providing this extremely useful examples.

I am facing the following issue when I try to build this examples. Am I missing something? I think it should work.

```
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for module 'gtkmm-3.0'
--   Found gtkmm-3.0, version 3.24.2
CMake Error at src/PictureBox/CMakeLists.txt:39 (configure_file):
  configure_file Problem configuring file


CMake Error at src/PictureBox/CMakeLists.txt:40 (configure_file):
  configure_file Problem configuring file


CMake Error at src/PictureBox/CMakeLists.txt:41 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
```

Edit: the lines that give error are these:

``` cmake
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Resources/Logo.png ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Resources/Logo.png COPYONLY)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Resources/Logo.png ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Debug/Resources/Logo.png COPYONLY)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Resources/Logo.png ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Release/Resources/Logo.png COPYONLY)
```

**Comment by gammasoft71** [comment]
Sorry for for the late response.
CMakeLists.txt fixed  : CMAKE_RUNTIME_OUTPUT_DIRECTORY replaced by CMAKE_CURRENT_BINARY_DIR.

**Comment by arrufat** [comment]
Thank you! :)

**Comment by dappchandu** [comment]
Boost: RelWithDebInfo build, shared libraries, MPI OFF, Python OFF, testing OFF
-- Boost.Cobalt: not building, can't include <coroutine>.
-- Boost.Context: architecture x86_64, binary format elf, ABI sysv, assembler gas, suffix .S, implementation fcontext
-- Boost.Fiber: NUMA target OS is linux
-- Boost.Iostreams: ZLIB ON, BZip2 OFF, LZMA OFF, Zstd OFF
-- Found the following ICU libraries:
--   data (required)
--   i18n (required)
--   uc (required)
-- Boost.Locale: iconv ON, ICU ON, POSIX ON, std ON, winapi OFF
-- Boost.Math: standalone mode OFF
-- Boost.Multiprecision: standalone mode OFF
-- Found the following ICU libraries:
--   data (required)
--   i18n (required)
--   uc (required)
-- Boost.Stacktrace: noop ON, backtrace ON, addr2line ON, basic ON, windbg OFF, windbg_cached OFF
-- Boost.Thread: threading API is pthread
-- Using boost version: 107100
-- Checking for module 'automotive-dlt >= 2.11'
--   No package 'automotive-dlt' found
-- Checking for module 'libsystemd'
--   No package 'libsystemd' found
-- Systemd was not found, watchdog disabled!
-- Default configuration folder: /etc/vsomeip
-- Default configuration file: /etc/vsomeip.json
Predefined base path: /tmp
Predefined unicast address: 127.0.0.1
Predefined diagnosis address: 0x01
Predefined wait times for internal communication ports (TCP): 100 (max=10000)
CMake Error at external/vsomeip/CMakeLists.txt:551 (configure_file):
  configure_file attempted to configure a file:
  /home/chandrakala/Desktop/FOTA_PROJECT_TEMPLATE/external/vsomeip/implementation/configuration/include/internal.hpp
  into a source directory.


-- Configuring incomplete, errors occurred!
See also "/home/chandrakala/Desktop/FOTA_PROJECT_TEMPLATE/build/debug/CMakeFiles/CMakeOutput.log".
See also "/home/chandrakala/Desktop/FOTA_PROJECT_TEMPLATE/build/debug/CMakeFiles/CMakeError.log".
make: *** [Makefile:65: all] Error 1

**Comment by dappchandu** [comment]
> Sorry for for the late response. CMakeLists.txt fixed : CMAKE_RUNTIME_OUTPUT_DIRECTORY replaced by CMAKE_CURRENT_BINARY_DIR.

for me the issue is not resolved it's like same error above-- 
-- Boost: RelWithDebInfo build, shared libraries, MPI OFF, Python OFF, testing OFF
-- Boost.Cobalt: not building, can't include <coroutine>.
-- Boost.Context: architecture x86_64, binary format elf, ABI sysv, assembler gas, suffix .S, implementation fcontext
-- Boost.Fiber: NUMA target OS is linux
-- Boost.Iostreams: ZLIB ON, BZip2 OFF, LZMA OFF, Zstd OFF
-- Found the following ICU libraries:
--   data (required)
--   i18n (required)
--   uc (required)
-- Boost.Locale: iconv ON, ICU ON, POSIX ON, std ON, winapi OFF
-- Boost.Math: standalone mode OFF
-- Boost.Multiprecision: standalone mode OFF
-- Found the following ICU libraries:
--   data (required)
--   i18n (required)
--   uc (required)
-- Boost.Stacktrace: noop ON, backtrace ON, addr2line ON, basic ON, windbg OFF, windbg_cached OFF
-- Boost.Thread: threading API is pthread
-- Using boost version: 107100
-- Checking for module 'automotive-dlt >= 2.11'
--   No package 'automotive-dlt' found
-- Checking for module 'libsystemd'
--   No package 'libsystemd' found
-- Systemd was not found, watchdog disabled!
-- Default configuration folder: /etc/vsomeip
-- Default configuration file: /etc/vsomeip.json
Predefined base path: /tmp
Predefined unicast address: 127.0.0.1
Predefined diagnosis address: 0x01
Predefined wait times for internal communication ports (TCP): 100 (max=10000)
CMake Error at external/vsomeip/CMakeLists.txt:551 (configure_file):
  configure_file attempted to configure a file:
  /home/chandrakala/Desktop/FOTA_PROJECT_TEMPLATE/external/vsomeip/implementation/configuration/include/internal.hpp
  into a source directory.


-- Configuring incomplete, errors occurred!
See also "/home/chandrakala/Desktop/FOTA_PROJECT_TEMPLATE/build/debug/CMakeFiles/CMakeOutput.log".
See also "/home/chandrakala/Desktop/FOTA_PROJECT_TEMPLATE/build/debug/CMakeFiles/CMakeError.log".
make: *** [Makefile:65: all] Error 1

**Comment by gammasoft71** [comment]
Hello,

first of all, thank you for your interest in my project.

I've tested it on Ubuntu 22.04, gcc 12.3, and CMake 3.22 and it works fine.

Can you tell me your configuration?

**Comment by dappchandu** [comment]
ubuntu 20.04.6
gcc-9.4
cmake -3.16.3

**Comment by dappchandu** [comment]
This error is while adding vsomeip as git submodule to my project

**Comment by gammasoft71** [comment]
I don't know `vsomeip`. But I've tested it on Ubuntu 20.04, gcc 11, and CMake 3.16 and it works fine too.
I think it's not a bug in my project but in your linux configuration.

**Comment by dappchandu** [comment]
I have tried the vsomeip 2.1 with other project , clonning some random github link and it's working fine . But vsomeip 3.4.10 is not working for me

**Comment by gammasoft71** [comment]
I don't know `vsomeip`... sorry...

**Comment by dappchandu** [comment]
Ok , will search for it.

**Comment by dappchandu** [comment]
Any ways thanks for the reply
